name: Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - name: Fetch dependencies
        run: npm ci
      - name: Package binaries
        run: |
          npm run build
          zip --junk-paths dist/polyglot-code-offline-layout-linux.zip dist/polyglot-code-offline-layout-linux README.md CHANGELOG.md
          zip --junk-paths dist/polyglot-code-offline-layout-macos.zip dist/polyglot-code-offline-layout-macos README.md CHANGELOG.md
          zip --junk-paths dist/polyglot-code-offline-layout-win.zip dist/polyglot-code-offline-layout-win.exe README.md CHANGELOG.md
      - name: Release
          uses: antonyurchenko/git-release:3.4.1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            DRAFT_RELEASE: "false"
            PRE_RELEASE: "false"
            CHANGELOG_FILE: "CHANGELOG.md"
            ALLOW_EMPTY_CHANGELOG: "false"
            ALLOW_TAG_PREFIX: "true"
          with:
            args: |
                dist/*.zip
